### PR TITLE
New python 3 PR

### PR DESCRIPTION
**Pull request by llazzaro**
Tested code on python2 and python 3.
I was using this package from another (with imports).
Now every test was done using the command "knockpy".
I also fixed xrange incompatibility (It was removed on python3)
tabs removed on some files

Let me know if there is any issue.

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
@guelfoweb ping please? the package is getting autoremoved from Debian testing soon...

**Comment by llazzaro** [comment]
I think this was reverted since it borke python2

**Comment by LocutusOfBorg** [comment]
Now that python2 is not a thing anymore... we can ignore python2 being broken?
btw, I think the current devel branch is 4.1, can you please rebase it on top of that one?

**Comment by drego85** [comment]
Python3 is implemented in the new version of Knock.

**Pull request closed without merging**
