### PR TITLE
Make knockpy compatible with python 2 and 3

### PR DESCRIPTION
**Pull request by Borim7**
Hey,

python 2 reachs end of live soon, so it is better to move to python 3.
Provide a version that is compatible with python 2 and 3 to make transition easier.

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
@Borim7 can you please also add this patch?
```
--- knockpy-4.1.0.orig/knockpy/knockpy.py
+++ knockpy-4.1.0/knockpy/knockpy.py
@@ -1,12 +1,12 @@
 #!/usr/bin/env python
 # -*- coding: utf-8 -*-

-from modules import zonetransfer
-from modules import header
-from modules import resolve
-from modules import wildcard
-from modules import save_report
-from modules import virustotal_subdomains
+from knockpy.modules import zonetransfer
+from knockpy.modules import header
+from knockpy.modules import resolve
+from knockpy.modules import wildcard
+from knockpy.modules import save_report
+from knockpy.modules import virustotal_subdomains

 try:
        from urllib.parse import urlparse
--- knockpy-4.1.0.orig/setup.py
+++ knockpy-4.1.0/setup.py
@@ -61,6 +61,10 @@ setup(
         'Programming Language :: Python :: 2',
         'Programming Language :: Python :: 2.6',
         'Programming Language :: Python :: 2.7',
+        'Programming Language :: Python :: 3',
+        'Programming Language :: Python :: 3.6',
+        'Programming Language :: Python :: 3.7',
+        'Programming Language :: Python :: 3.8',
     ],

     keywords='knock sudbomain scan',

```

I had to add the above bits to avoid a failure during startup. (the import hack seems not compatible with python2)
```
knockpy --help
Traceback (most recent call last):
  File "/usr/bin/knockpy", line 11, in <module>
    load_entry_point('knockpy==4.1.1', 'console_scripts', 'knockpy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/knockpy/knockpy.py", line 4, in <module>
    from modules import zonetransfer
ModuleNotFoundError: No module named 'modules'
```

cat /usr/bin/knockpy
```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'knockpy==4.1.1','console_scripts','knockpy'
__requires__ = 'knockpy==4.1.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('knockpy==4.1.1', 'console_scripts', 'knockpy')()
    )
```
```
find /usr/lib/python3/dist-packages/knockpy
/usr/lib/python3/dist-packages/knockpy
/usr/lib/python3/dist-packages/knockpy/__pycache__
/usr/lib/python3/dist-packages/knockpy/__pycache__/knockpy.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/__pycache__/__init__.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/__init__.py
/usr/lib/python3/dist-packages/knockpy/knockpy.py
/usr/lib/python3/dist-packages/knockpy/config.json
/usr/lib/python3/dist-packages/knockpy/modules
/usr/lib/python3/dist-packages/knockpy/modules/__pycache__
/usr/lib/python3/dist-packages/knockpy/modules/__pycache__/wildcard.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/modules/__pycache__/save_report.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/modules/__pycache__/header.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/modules/__pycache__/zonetransfer.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/modules/__pycache__/__init__.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/modules/__pycache__/virustotal_subdomains.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/modules/__pycache__/resolve.cpython-36.pyc
/usr/lib/python3/dist-packages/knockpy/modules/header.py
/usr/lib/python3/dist-packages/knockpy/modules/resolve.py
/usr/lib/python3/dist-packages/knockpy/modules/zonetransfer.py
/usr/lib/python3/dist-packages/knockpy/modules/__init__.py
/usr/lib/python3/dist-packages/knockpy/modules/virustotal_subdomains.py
/usr/lib/python3/dist-packages/knockpy/modules/wildcard.py
/usr/lib/python3/dist-packages/knockpy/modules/save_report.py
/usr/lib/python3/dist-packages/knockpy/wordlist
/usr/lib/python3/dist-packages/knockpy/wordlist/wordlist.txt
```

**Comment by LocutusOfBorg** [comment]
Don't know why, but the import fails if I prepend knockpy.modules

**Comment by Borim7** [comment]
@LocutusOfBorg with which python version did you check?

I tested with Python 3.7.6 and Python 2.7.17 on a windows machine and without installing knockpy. I just use it directly from the repo.

The result of the find command looks like you have installed knockpy. With which command did you install it?

**Comment by LocutusOfBorg** [comment]
I did create with the standard packaging guidelines for Debian,
you can see the deb file here:
https://packages.qa.debian.org/k/knockpy.html
and also the build log
https://buildd.debian.org/status/package.php?p=knockpy&suite=unstable

**Comment by Borim7** [comment]
I switched to linux to test the issue. The problem is that during the include it differs what is visible, depending if knockpy is installed or directly used.

With your patch the installed knockpy works, but when executed directly its complain, that no module knockpy exists:

> ModuleNotFoundError: No module named 'knockpy.modules'; 'knockpy' is not a package

I take a look how both cases can be satisfied.

**Comment by Borim7** [comment]
@LocutusOfBorg I modified your patch so it is compatible with python 2.

It is not possible to preserve the python 2 behaviour 100%. When you want to execute knockpy from repository you have to use `python -m knockpy.knockpy`. This load knockpy as module and execute it afterwards.

Due to the changes in python 3 import behaviour you have to separate script files from packages. The mixed usage of python 2 seems no longer possible.

When using knockpy as installed package nothing changes.

**Comment by LocutusOfBorg** [comment]
thanks! I reuploaded the updated patch in Debian!

**Comment by drego85** [comment]
Knock v5 is now compatible with Python3!

**Pull request closed without merging**
