### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by x-f1v3**
fix bug

```
Traceback (most recent call last):
  File "/usr/local/bin/knockpy", line 33, in <module>
    sys.exit(load_entry_point('knockpy==5.0.0', 'console_scripts', 'knockpy')())
  File "/usr/local/lib/python3.6/dist-packages/knockpy-5.0.0-py3.6.egg/knockpy/knockpy.py", line 431, in main
    print (Output.headerPrint(local, google, duckduckgo, virustotal, domain))
  File "/usr/local/lib/python3.6/dist-packages/knockpy-5.0.0-py3.6.egg/knockpy/knockpy.py", line 155, in headerPrint
    ip_req = req[2][0]
IndexError: list index out of range
```

### CODE REVIEW

**Comment by guelfoweb** [comment]
thanks @x-f1v3 merged!

**Comment by dinesh-venkatesan** [comment]
Hello @guelfoweb ,
I still facing the error. Last night it worked fine however it started throwing the error. I'm using docker

```
Traceback (most recent call last):
  File "knockpy/knockpy.py", line 499, in <module>
    main()
  File "knockpy/knockpy.py", line 430, in main
    print (Output.headerPrint(local, google, duckduckgo, virustotal, domain))
  File "knockpy/knockpy.py", line 154, in headerPrint
    ip_req = req[2][0]
IndexError: list index out of range
```

**Comment by x-f1v3** [comment]
@dinesh-venkatesan  What is the domain used

**Comment by dinesh-venkatesan** [comment]
Hello @x-f1v3 I tried the same again now. It works fine now. I don't what was the reason :/ 

Will post here if anything comes up again.

**Comment by dinesh-venkatesan** [comment]
It shows error whenever I run it for `intercomcdn.com` domain. I think this might help.

@x-f1v3

**Comment by x-f1v3** [comment]
no problem here

**Comment by dinesh-venkatesan** [comment]
@x-f1v3 Are you running it via [docker](https://hub.docker.com/r/nocommentlab/knock) ?

**Comment by x-f1v3** [comment]
the version of knock  in docker does not seem to be the latest version

**Pull request merged**
